# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35403c289b956b19c5805c0a1dc5d9390b3dc4a11ef572fc55ce0c75896507c294549b3e84810b355c7c4e914b95ac94c199b0cd4c7823e1f8889f31f9757c92

test:
  secret_key_base: 524f08821cadf21953cbe90668cfcd05c1bb5ec9986580e68f54132127eff32918f3e67ce4a0ad0f9714badde873d485c08c936f1539f0ff25d1b133dca0756e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
